import test from 'node:test';
import assert from 'node:assert/strict';
import {makePreset,sample,putKey,validateProject,cameraMotion} from './2026-09-20-model.mjs';
test('every preset survives JSON roundtrip',()=>{for(const name of ['dialogue','product','walk','blank']){const p=makePreset(name);assert.deepEqual(validateProject(JSON.parse(JSON.stringify(p))),p);}});
test('sampling interpolates and clamps without mutating the base',()=>{const o=makePreset('walk').objects[0];const original=JSON.stringify(o);assert.equal(sample(o,0).position[0],-3);assert.equal(sample(o,3).position[0],0);assert.equal(sample(o,6).position[0],3);assert.equal(sample(o,99).position[0],3);assert.equal(JSON.stringify(o),original);});
test('key insertion replaces same-time pose and sorts',()=>{const o=makePreset('blank').camera;const pose=sample(o,0);putKey(o,4,pose);putKey(o,2,{...pose,position:[1,2,3]});putKey(o,2,{...pose,position:[4,5,6]});assert.equal(o.keys.length,2);assert.deepEqual(o.keys[0].position,[4,5,6]);});
test('invalid project rejected rather than silently accepted',()=>{for(const change of [p=>p.duration=NaN,p=>p.objects.push({...p.objects[0]}),p=>p.camera.position=[1,2],p=>p.objects[0].kind='script',p=>p.objects[0].scale=[0,1,1],p=>p.camera.keys=[{time:100,position:[1,2,3],rotation:[0,0,0],scale:[1,1,1]}]]){const p=makePreset('dialogue');change(p);assert.throws(()=>validateProject(p));}});
test('all camera motions are editable keyframes inside duration',()=>{for(const motion of ['static','dolly','truck','orbit']){const p=makePreset('product');cameraMotion(p,motion);assert.ok(p.camera.keys.length>=1);validateProject(p);if(motion!=='static')assert.notDeepEqual(sample(p.camera,0).position,sample(p.camera,p.duration).position);}});
test('rotation takes shortest angular path',()=>{const o=makePreset('blank').camera;o.keys=[];putKey(o,0,{position:[0,0,0],rotation:[0,Math.PI*179/180,0],scale:[1,1,1]});putKey(o,2,{position:[0,0,0],rotation:[0,-Math.PI*179/180,0],scale:[1,1,1]});assert.ok(Math.abs(Math.abs(sample(o,1).rotation[1])-Math.PI)<0.001);});
